<a href="https://colab.research.google.com/github/Jefferson-Pedro/BigData-com-Python/blob/main/Exercicio_Aula06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio 1 – Leia o arquivo “analise_homicidio.csv” e faça o tratamento dos dados  lidos com split(), de tal forma que os dados fiquem nas colunas exatas nas listas.

Dados lidos com problema:
['No;DATA;HORA;INCIDENTE;SEXO;IDADE;MUNICÍPIO']
['41290653;01/01/2020;03:27;HOMICÍDIO', 'DOLOSO;M;27;VILA', 'VELHA']


Dados lidos e corrigidos:
['No;DATA;HORA;INCIDENTE;SEXO;IDADE;MUNICÍPIO']
['41290653;01/01/2020;03:27;HOMICÍDIO DOLOSO;M;27;VILA VELHA']

In [47]:
import pandas as pd
arquivo = 'analise_homicidio.csv'
ler = pd.read_csv(arquivo, sep=";")
display(ler)

,No,DATA,HORA,INCIDENTE,SEXO,IDADE,MUNICÍPIO
0,41290653,01/01/2020,03:27,HOMICÍDIO DOLOSO,M,27,VILA VELHA
1,41291841,01/01/2020,08:10,HOMICÍDIO DOLOSO,M,39,SERRA
2,41292282,01/01/2020,09:38,HOMICÍDIO DOLOSO,M,44,BOA ESPERANCA
3,41292728,01/01/2020,10:49,HOMICÍDIO DOLOSO,M,42,BOM JESUS DO NORTE
4,41300399,02/01/2020,11:48,HOMICÍDIO DOLOSO,F,61,VILA VELHA
...,...,...,...,...,...,...,...
1159,43970170,30/12/2020,20:36,HOMICÍDIO DOLOSO,M,52,CARIACICA
1160,43974873,31/12/2020,13:49,HOMICÍDIO DOLOSO,M,NaN,SANTA LEOPOLDINA
1161,43976716,31/12/2020,18:07,HOMICÍDIO DOLOSO,M,16,CARIACICA
1162,INCIDENTE,QUANT,NaN,NaN,NaN,NaN,NaN
1163,TOTAL,1162,NaN,NaN,NaN,NaN,NaN

In [ ]:
import csv

with open('analise_homicidio.csv', "r") as arquivo:
  ler = csv.reader(arquivo, delimiter=";")
  for i, linha in enumerate(ler):
    print(linha)